### ISSUE TITLE
Path problem on Unix based FTP 

### ISSUE THREAD

**Issue by GPSMAGIC** [sindresorhus/jsftp-mkdirp#2]
# General 

On Unix based FTP servers using a path that contains '//' returns error code 553 :scream: While on Windows based FTP servers there is no error :clap:. 

## Solution 
Using the following code to change the path to work with Windows and Unix :white_check_mark:

```javascript

remotePath = remotePath.replace(/\\/g, '/').replace(/\/\//g, '/');

```
Enjoy :tada:

**Comment by sindresorhus** [comment]
Why are you posting it this here? Are you having problems creating a directory? What kind of path does not work?

**Comment by GPSMAGIC** [comment]
The path is something like this: aaaaa//bbbbb//ccccc path. 
Windows based FTP handel this with no problem but Unix based FTP return error code 553.
causing jsftp-mkdirp to fail. 

I posted it here so the issue will be known and either someone can use the info or solve the problem.

**Comment by sindresorhus** [comment]
So why not just use a normal Unix path which from the looks of it will work on both?
