### ISSUE TITLE
insufficient error handling

### ISSUE THREAD

**Issue by hasufell** [sindresorhus/jsftp-mkdirp#4]
This hides issues. I don't see how that is correct error handling. On permissions errors, the mkdirp function will just do nothing instead of properly failing.

```js
			.catch(err => {
				if (err.code === 550) {
					if (dirs.length > 0) {
						return mkdir(dirs.pop());
					}

					return;
				}

				err.message += ` - mkd: ${dir}`;
				throw err;
			});
```

**Comment by sindresorhus** [comment]
How is it incorrect exactly? How would you change it?

If `mkdir` throws an error it will bubble up the promise chain. We only catch the `550` error.

**Comment by hasufell** [comment]
> How is it incorrect exactly? How would you change it?

Because you _never_ propagate the `550` error. If you have no permissions whatsoever, the codepath will end up doing `return;` as you can see above.

**Comment by hasufell** [comment]
Yeah, I guess that should work.
