### ISSUE TITLE
mkdirp fails if the full destination directory already exists

### ISSUE THREAD

**Issue by hasufell** [sindresorhus/jsftp-mkdirp#6]
Now I started using the new version and the behavior is still a bit odd and not exactly like `mkdir -p`.

If you run `mkdirp` on a full directory that already exists, it will throw a `550` error, because `(err.code === 550 && dirs.length > 0)` will be false, see https://github.com/sindresorhus/jsftp-mkdirp/blob/master/index.js#L28

I think we need multiple ftp commands here to properly map the expected `mkdir -p` behavior on ftp level.  The algorithm should look like this in pseudocode, just to give an idea:
```
INPUT: path

old_pwd = ftp.raw.pwd();

components = reverse(parentDirs(path));

Promise.mapSeries(components, function(component) {
    if (ftp.cwd(component) == error[550]) {
      return ftp.raw.mkd(component);
    } else {
      return true;
    }
  }).finally(function() {
    ftp.raw.cwd(old_pwd);
  })
```

So we basically just try to cd into each path component, if that fails at any point... run `ftp.raw.mkd` on that path component without _any_ error handling. Because if we cannot cd into an ftp directory and cannot create it, then everything is lost.

This will still do the expected thing wrt #4

**Comment by sindresorhus** [comment]
Yup, you're right. The algorithm looks good. Interested in doing a pull request? I probably won't have time to get to this in the near future.

**Comment by hasufell** [comment]
I came up with something like this:

```js
	// these are all absolute, e.g. for '/foo/bar/baz' this
	// is ['/', '/foo', '/foo/bar' '/foo/bar/baz']
	const pathComponents = dirs.reverse();

	return Promise.mapSeries(pathComponents, component => {
		// try to change the working directory to figure out
		// if the target directory already exists...
		return Promise.promisify(this.raw.cwd)(component)
			.catch(error => {
				// ...if that fails, create the dir
				if (error.code === 550) {
					return Promise.promisify(this.raw.mkd)(component)

					.catch(err => {
						err.message += ` - mkd: ${component}`;
						throw err;
					});
				}
				throw error;
			});
	});
```

However, that will change the current working directory. For restoring it, we need to save the old working directory, but it seems the ftp [PWD](https://tools.ietf.org/html/rfc959#page-32) command does not have a properly defined result format, so stuff like [this](https://github.com/sergi/jsftp/blob/master/test/jsftp_test.js#L286) may or may not work.

Instead, we can use the [MLST](https://tools.ietf.org/html/rfc3659#page-23), which has a properly defined format, which can be reliably parsed. That would also eliminate the need for `CWD`.

However, [jsftp doesn't seem to provide MLST yet](https://github.com/sergi/jsftp/issues/187).

**Comment by sindresorhus** [comment]
I see. Hmm, maybe we could execute MLST manually for now using the `raw` method.

**Comment by hasufell** [comment]
> Hmm, maybe we could execute MLST manually for now using the raw method.

That's the point. You can't, unless `mlst` is in [this list](https://github.com/sergi/jsftp/blob/master/lib/jsftp.js#L30). It's sort of a whitelist for the `raw` commands.

**Comment by ArtskydJ** [comment]
jsftp now supports execution of `mlst`. https://github.com/sergi/jsftp/issues/187
